apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::963681622169:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZDWUQDZ72S74\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::iam::963681622169:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build    \n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T16:29:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "35818"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6270a587-243e-4459-a3b4-ec1b746343f7
