apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963681622169:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-V8K7IZGC7MTL
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-27T16:18:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1301"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8baf9df8-68fc-46e4-99b0-b79d202fc42f
